// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDug1Ud-HWlWvY0IIkwopNOWYZUYjyhkZY',
    appId: '1:344147872340:web:806469a839a04ed03a7bc1',
    messagingSenderId: '344147872340',
    projectId: 'wedwheel',
    authDomain: 'wedwheel.firebaseapp.com',
    storageBucket: 'wedwheel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfItxMZetw8Qowlz_L5ikZi6KcZKydG8E',
    appId: '1:344147872340:android:d23ef0aa4aa61fa33a7bc1',
    messagingSenderId: '344147872340',
    projectId: 'wedwheel',
    storageBucket: 'wedwheel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_fZQxPRIZhg488jb2SavXAM1D0FQW_UY',
    appId: '1:344147872340:ios:b30afac84bdda17e3a7bc1',
    messagingSenderId: '344147872340',
    projectId: 'wedwheel',
    storageBucket: 'wedwheel.appspot.com',
    iosBundleId: 'com.example.wedweel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_fZQxPRIZhg488jb2SavXAM1D0FQW_UY',
    appId: '1:344147872340:ios:b30afac84bdda17e3a7bc1',
    messagingSenderId: '344147872340',
    projectId: 'wedwheel',
    storageBucket: 'wedwheel.appspot.com',
    iosBundleId: 'com.example.wedweel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDug1Ud-HWlWvY0IIkwopNOWYZUYjyhkZY',
    appId: '1:344147872340:web:81aba5713f49683f3a7bc1',
    messagingSenderId: '344147872340',
    projectId: 'wedwheel',
    authDomain: 'wedwheel.firebaseapp.com',
    storageBucket: 'wedwheel.appspot.com',
  );
}
